// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8h9cV_L3Rk1TOGkWibwvieN0A5KfsW_k',
    appId: '1:1017659490970:web:aa9f047b4c03c8ee749523',
    messagingSenderId: '1017659490970',
    projectId: 'onlinemarketplace-9eb11',
    authDomain: 'onlinemarketplace-9eb11.firebaseapp.com',
    storageBucket: 'onlinemarketplace-9eb11.appspot.com',
    measurementId: 'G-CY1LCQ9VSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgQuHMo-xA0uyVbNKabfc3GFYJiyLrR7M',
    appId: '1:1017659490970:android:892c94ad19d0a01f749523',
    messagingSenderId: '1017659490970',
    projectId: 'onlinemarketplace-9eb11',
    storageBucket: 'onlinemarketplace-9eb11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmAK8OtIVSHhXjGf5j0WyJGhwlbhl_pdM',
    appId: '1:1017659490970:ios:5f3e3b97ecd4f5c3749523',
    messagingSenderId: '1017659490970',
    projectId: 'onlinemarketplace-9eb11',
    storageBucket: 'onlinemarketplace-9eb11.appspot.com',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmAK8OtIVSHhXjGf5j0WyJGhwlbhl_pdM',
    appId: '1:1017659490970:ios:5f3e3b97ecd4f5c3749523',
    messagingSenderId: '1017659490970',
    projectId: 'onlinemarketplace-9eb11',
    storageBucket: 'onlinemarketplace-9eb11.appspot.com',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8h9cV_L3Rk1TOGkWibwvieN0A5KfsW_k',
    appId: '1:1017659490970:web:24d5ed5a3136f4a4749523',
    messagingSenderId: '1017659490970',
    projectId: 'onlinemarketplace-9eb11',
    authDomain: 'onlinemarketplace-9eb11.firebaseapp.com',
    storageBucket: 'onlinemarketplace-9eb11.appspot.com',
    measurementId: 'G-MCVCYDZB7W',
  );
}
